# Generated by Django 2.1.3 on 2019-03-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=165)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='address.Locality')),
            ],
            options={
                'verbose_name_plural': 'Neighborhoods',
                'ordering': ('locality', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('name', 'postal_code', 'locality')},
        ),
    ]
