# Generated by Django 2.2 on 2019-06-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
